version: '3.8'

services:
  cake_db:
    container_name: cake_app_db
    image: postgres:13-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TZ: UTC
    volumes:
      - "./.storage/postgresql/:/var/lib/postgresql/data"
