Type: AWS::S3::Bucket
Properties:
  BucketName: cake-images
  PublicAccessBlockConfiguration:
    RestrictPublicBuckets: true
  CorsConfiguration:
    CorsRules:
      -
        AllowedOrigins:
          - '*'
        AllowedHeaders:
          - '*'
        AllowedMethods:
          - PUT
          - POST
          - GET
          - DELETE
          - HEAD
        MaxAge: 3000
